spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bora}
    username: ${SPRING_DATASOURCE_USERNAME:bora}
    password: ${SPRING_DATASOURCE_PASSWORD:bora123}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
server:
  port: ${PORT:8080}
springdoc:
  swagger-ui:
    path: /swagger-ui.html
